version: "3.9"

services: 
  postgres:
    image: postgres:15
    container_name: payflow-postgres
    restart: always
    environment:
      POSTGRES_USER: payflow
      POSTGRES_PASSWORD: payflow
      POSTGRES_DB: payflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: payflow-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: payflow-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: payflow
      RABBITMQ_DEFAULT_PASS: payflow


  pgadmin:
    image: dpage/pgadmin4
    container_name: payflow-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@payflow.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data: